Feature/cheat
Vinno97/prism pull request #49
Opened 2018-11-16 19:17 UTC by cornest

2018-11-19 15:39 UTC, BenKrocke requested changes
Paar dingetjes

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/include/ECS/Components/HealthComponent.h
> +				HealthComponent* component = new HealthComponent();
Unique of shared ptr?

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/include/ECS/Systems/AttackSystem.h
> +using namespace ECS::Systems;
Geen using namespaces in de header

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/include/ECS/Systems/MotionSystem.h
> +using namespace ECS::Systems;
Zelfde verhaal, moet eruit

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/src/ECS/EntityManager.cpp
>  				Entity<Component*> entity;
Ik ben hier te dom voor maar is een Component pointer type wat je wilt? Moet dit geen unique ptr zijn aangezien je hem ook terug pusht?

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/src/ECS/Systems/AttackSystem.cpp
> +	for (auto entity : entityManager->getAllEntitiesWithComponent<BoundingBoxComponent>())
Dit is een zieke nesting loop, zou wellicht wat mooier gerefactored kunnen worden?

2018-11-19 15:39 UTC, BenKrocke commented on Prism.Engine/src/ECS/Systems/CheatSystem.cpp
> +		if (ticks > 0) {
Qua code style zou ik hier 'if else' van maken tenzij je in 1 loop van ticks 0 naar 1 of 6 naar 7 naar 0 wil gaan?

2018-11-21 10:05 UTC, cornest commented on Prism.Engine/include/ECS/Components/HealthComponent.h
> +				HealthComponent* component = new HealthComponent();
Kan, maar dat kunnen we beter niet in deze branch doen

2018-11-26 13:21 UTC, cornest commented
Cheatoptions:
R = increasen van resources (+100 per keer)
H = increasen van health (+100 per keer)

T = decreasen van resources (-100 per keer, wanneer het al minder is dan 100 wordt het naar 0 gezet) 
J = decreasen van resources (-100 per keer, wanneer het al minder is dan 100 wordt het naar 0 gezet)

Numpad:
'+' = increasen van snelheid
'-' = decreasen van snelheid

END = Snelheid restten

2018-12-03 10:49 UTC, BenKrocke submitted a review, later dismissed

2018-12-03 10:49 UTC, BenKrocke commented on Prism.Game/src/ECS/Systems/KeyboardInputSystem.cpp
> +						// healthComponent->increase();
Moet dit gecomment zijn?

2018-12-03 12:48 UTC, mowie2 submitted a review, later dismissed

2018-12-03 15:28 UTC, DaanWillems approved these changes

2018-12-03 15:31 UTC, BenKrocke approved these changes

2018-12-03 15:31 UTC, merged