Feature/text rendering
Vinno97/prism pull request #76
Opened 2018-12-02 15:23 UTC by DaanWillems

2018-12-02 16:25 UTC, Vinno97 requested changes

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/MenuBuilder.cpp
> +	TextControl& MenuBuilder::addTextControl(float x, float y, float width, float height, std::string text)
Ik gok dat deze functie niet getest is? 
`textControl` is namelijk aangemaakt op de stack en wordt verwijderd zodra de functie verlaten wordt. Een reference hiernaar returnen zal dan naar willekeurig geheugen wijzen

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/Menu.cpp
> +		for (auto const& control : other.textControls) {
Ik zie geen raw pointers gebruikt worden. Zijn deze move/copy constructors/operators daadwerkelijk nodig?

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/MenuRenderer.cpp
> +		projection = glm::ortho(0.0f, 800.0f, 0.0f, 600.0f);
Wat zijn dit voor hard-coded waardes? Lijken zo op het eerste gezicht vrij arbitrair

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/TextRenderer.cpp
> +void TextRenderer::RenderText(Menu::TextControl control)
Dit kan const worden 
```cpp
void TextRenderer::RenderText(const Menu::TextControl control) const
```

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/TextRenderer.cpp
> +void TextRenderer::init()
Waarom staat deze lege functie hier?

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/TextRenderer.cpp
> +void TextRenderer::RenderText(Menu::TextControl control)
Tevens kan `control` by reference worden meegegeven

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Game/include/States/PrismGame.h
> +	PrismGame(const PrismGame & other) {
Pls no

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Game/res/saves/Sample Save.json
> +{"layers":[{"id":1,"name":"Objects","objects":[{"gid":0,"height":1.0,"id":0,"name":"","rotation":0.0,"type":"","visible":false,"width":1.0,"x":0.0,"y":0.0},{"gid":0,"height":1.0,"id":0,"name":"","rot
Waarom is deze gecommit  😓. Ik zal hem maar eens aan de `.gitignore` moeten toevoegen.

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/TextControl.cpp
> +#include "Menu/TextControl.h"
Deze file is overbodig

2018-12-02 16:25 UTC, Vinno97 commented on Prism.Engine/src/Menu/TextRenderer.cpp
> +			face->glyph->advance.x
CLion geeft hier de *error* (geen warning)
`Non-constant-expression cannot be narrowed from type 'FT_Pos' (aka 'long') to 'unsigned int' in initializer list`
Het compileert verder wel

2018-12-02 16:27 UTC, DaanWillems commented on Prism.Engine/src/Menu/MenuRenderer.cpp
> +		projection = glm::ortho(0.0f, 800.0f, 0.0f, 600.0f);
Deze worden niet meer gebruikt dus mogen ook weg (zal ik doen natuurlijk)

2018-12-02 16:33 UTC, DaanWillems commented on Prism.Game/include/States/PrismGame.h
> +	PrismGame(const PrismGame & other) {
rip die had ik gebruikt om te kijken waar de copy plaatsvond

2018-12-02 16:34 UTC, DaanWillems commented on Prism.Engine/src/Menu/TextControl.cpp
> +#include "Menu/TextControl.h"
uhm wat?

2018-12-03 10:50 UTC, Vinno97 submitted a review, later dismissed

2018-12-03 12:23 UTC, mowie2 submitted a review, later dismissed

2018-12-04 22:49 UTC, Vinno97 submitted a review, later dismissed

2018-12-05 12:18 UTC, cornest submitted a review, later dismissed

2018-12-05 13:27 UTC, photonman1997 submitted a review, later dismissed

2018-12-09 17:59 UTC, cornest approved these changes

2018-12-09 18:39 UTC, photonman1997 approved these changes

2018-12-10 09:20 UTC, merged