Add Resource Mine
Vinno97/prism pull request #83
Opened 2018-12-03 22:36 UTC by Vinno97

Changes:
* Ook op Linux wordt nu `c++17` gebruikt
* `Vector2<T>` toegevoegd voor uniforme 2D vector-berekeningen. PositionComponent is impliciet converteerbaar hiernaar
* Mine toegevoegd (dit is de daadwerkelijke resource collector)
* Resources weer compatible gemaakt met meerdere collectors (er was wel code hiervoor, maar het was niet volledig geïmplementeerd)

2018-12-03 23:05 UTC, DaanWillems requested changes

2018-12-03 23:05 UTC, DaanWillems commented on Prism.Game/src/ECS/Systems/ResourceGatherSystem.cpp
> +                // Zoekt de dichtstbijzijnde gatherer.
Ik ben zelf niet zo'n voorstander van nederlandse comments tussen engelse code

2018-12-03 23:05 UTC, DaanWillems commented on Prism.Engine/include/Math/Vector2.h
> +            T length = std::sqrt((x * x) + (y * y));
Deze code wordt gedeeld tussen normalize en distance dus naar mijn mening is een length method die dit uitvoert wel netjes

2018-12-03 23:14 UTC, DaanWillems approved these changes

2018-12-04 14:43 UTC, BenKrocke approved these changes

2018-12-04 14:43 UTC, BenKrocke commented on Prism.Game/src/World/Assemblers/MineAssembler.cpp
> +    if (worldObject.gid == 9)
Komt deze nog overeen met de huidige codes?

2018-12-04 16:57 UTC, merged