Patch/collision fps
Vinno97/prism pull request #98
Opened 2018-12-06 09:10 UTC by LL16

2018-12-09 15:38 UTC, DaanWillems requested changes

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Engine/include/Physics/BoundingBox.h
> +		/// Get the south co�rdinate of the boundingbox
ö nö dit is föut

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Engine/include/Physics/QuadTree.h
>  		/// <param name="width">The center x co�rdinate of the highest level quadtree</param>
Deze summary klopt geloof ik niet

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Engine/src/Physics/QuadTree.cpp
> +	//bool fitTop = bNorth <= qNorth && bSouth >= qY;
Is dit nog nodig?

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Game/src/States/PrismGame.cpp
> +			//.registerSystem<2, ResourceGatherSystem>(entityManager)
Deze systems staan denk ik perongeluk nog uit

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Game/src/States/PrismGame.cpp
> +		std::cout << "FPS:   \t" << 1.0 / context.deltaTime << std::endl;
Ik zou deze nog ff weghalen want std::cout is relatief zwaar om uit te voeren
https://stackoverflow.com/questions/43051948/why-is-stdcout-so-time-consuming?rq=1

2018-12-09 15:38 UTC, DaanWillems commented on Prism.Game/src/States/PrismGame.cpp
> +		//context.deltaTime *= 2.5;
Kan denk ik weg

2018-12-09 16:59 UTC, LL16 commented on Prism.Game/src/States/PrismGame.cpp
> +		std::cout << "FPS:   \t" << 1.0 / context.deltaTime << std::endl;
volgens mij zit de fps counter nog niet in development dus wil eigenlijk dee npog erin laten

2018-12-09 17:01 UTC, LL16 commented on Prism.Game/src/States/PrismGame.cpp
> +		//context.deltaTime *= 2.5;
die uit gecommente wel denk ik

2018-12-09 17:01 UTC, LL16 commented on Prism.Game/src/States/PrismGame.cpp
> +			//.registerSystem<2, ResourceGatherSystem>(entityManager)
jep

2018-12-09 17:01 UTC, LL16 commented on Prism.Engine/src/Physics/QuadTree.cpp
> +	//bool fitTop = bNorth <= qNorth && bSouth >= qY;
nee niet echt

2018-12-09 17:01 UTC, LL16 commented on Prism.Engine/include/Physics/QuadTree.h
>  		/// <param name="width">The center x co�rdinate of the highest level quadtree</param>
nope zeker niet

2018-12-09 17:16 UTC, LL16 commented on Prism.Engine/include/Physics/BoundingBox.h
> +		/// Get the south co�rdinate of the boundingbox
zäl hët vërändërën

2018-12-09 18:05 UTC, DaanWillems commented on Prism.Game/src/States/PrismGame.cpp
> +		//context.deltaTime *= 2.5;
die bedoelde ik idd

2018-12-09 18:05 UTC, DaanWillems commented on Prism.Game/src/States/PrismGame.cpp
> +		std::cout << "FPS:   \t" << 1.0 / context.deltaTime << std::endl;
Dan ff een TODO erbij met later weghalen want het zou zonde zijn als dit in de uiteindelijke versie zit

2018-12-09 18:06 UTC, DaanWillems submitted a review, later dismissed

2018-12-10 09:27 UTC, DaanWillems approved these changes

2018-12-10 09:27 UTC, photonman1997 approved these changes

2018-12-10 09:32 UTC, merged